# -*- coding: utf-8 -*-
"""team3 _taskone

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cms2_i_oH-7u2W-vC_VQfibMaM7LZOcd
"""

# import random

# text = './news.txt'
# f = open(text, "r")
# #print(f.read())
def taskOne():
  text = './news.txt'
  f = open(text, "r")
  p = f.read()
  a = p.count('a')
  e = p.count('e')
  i = p.count('i')
  o = p.count('o')
  u = p.count('u')
  t1 = f"a={a},e={e},i={i},o={o},u={u}"
  return t1


# def pickOneMemeber():
#     '''example function'''

#     teamJDE = ['hammer', 'billy', 'chistina']
#     result = random.sample(teamJDE, 1)
#     return result



if __name__ == "__main__":
  # print(pickOneMemeber())
  print(taskOne())
    # print(taskTwo())
    # print(taskThree())
    # print(taskFour())